### ISSUE TITLE
OnDemand is not working for gpu058 - PSC ticket #41372

### ISSUE THREAD

**Issue by julianx** [pscedu/aibd-pearc20#3]
PSC ticket: https://tickets.psc.edu/Ticket/Display.html?id=41372

The OnDemand process is not working for gpu058. The process for bringing the notebook up does show as running on the node, but no actual notebook is made available after waiting for 10 minutes.

ps -ef | grep julian
```
julian   71101 71096  0 15:20 ?        00:00:00 /bin/bash /var/slurmd/job9922510/slurm_script
julian   71155 71101  0 15:20 ?        00:00:00 /bin/bash -l /home/julian/ondemand/data/sys/dashboard/batch_connect/sys/jupyter_app/output/be06c07d-db7b-4dee-95e5-1f7af6911362/script.sh
julian   71190 71155  0 15:20 ?        00:00:01 /opt/packages/anaconda/anaconda3-5.1.0/bin/python /opt/packages/anaconda/anaconda3-5.1.0/bin/jupyter-notebook --config=/home/julian/ondemand/data/sys/dashboard/batch_connect/sys/jupyter_app/output/be06c07d-db7b-4dee-95e5-1f7af6911362/config.py
```
pstree

        ├─slurmstepd─┬─slurm_script───script.sh───jupyter-noteboo
        │            └─4*[{slurmstepd}]

![image](https://user-images.githubusercontent.com/566664/86283424-0a051e80-bbaf-11ea-901d-20236b9f78fb.png)

![image](https://user-images.githubusercontent.com/566664/86283447-15f0e080-bbaf-11ea-8f80-1a90d48f1fa9.png)

 /home/julian/ondemand/data/sys/dashboard/batch_connect/sys/jupyter_app/output/be06c07d-db7b-4dee-95e5-1f7af6911362/script.sh:
```#!/bin/bash -l

# Set working directory to home directory
cd "${HOME}"

#
# Start Jupyter Notebook Server
#

# Restore the module environment to avoid conflicts
# module restore
module purge

# Load the require modules
module load python3/3.4.2 AI/anaconda3-5.1.0_gpu

# Launch the Jupyter Notebook Server
jupyter notebook --config="${CONFIG_FILE}" 
```

Running the notebook command shows the service is up and using that specific port.

```
/opt/packages/anaconda/anaconda3-5.1.0/bin/python /opt/packages/anaconda/anaconda3-5.1.0/bin/jupyter-notebook --config=/home/julian/ondemand/data/sys/dashboard/batch_connect/sys/jupyter_app/output/be06c07d-db7b-4dee-95e5-1f7af6911362/config.py
[I 15:29:52.176 NotebookApp] Writing notebook server cookie secret to /run/user/72517/jupyter/notebook_cookie_secret
[W 15:29:53.210 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 15:29:53.212 NotebookApp] The port 63696 is already in use, trying another port.
[C 15:29:53.212 NotebookApp] ERROR: the notebook server could not be started because no available port could be found.
```

The connection to that port works from other nodes.
```
telnet gpu058 63696
Trying 10.4.219.218...
Connected to gpu058.
Escape character is '^]'.
```

**Comment by julianx** [comment]
It seems to happen because of an error when running the script. The return code might change and cause the service not to be made available: "Error loading server extension jupyter_tensorboard"
```
/opt/packages/anaconda/anaconda3-5.1.0/bin/python /opt/packages/anaconda/anaconda3-5.1.0/bin/jupyter-notebook --config=/home/julian/ondemand/data/sys/dashboard/batch_connect/sys/jupyter_app/output/e2411ce1-2f1b-4559-bd6b-e2ceaed0a6b0/config.py
[I 10:36:50.631 NotebookApp] Writing notebook server cookie secret to /run/user/72517/jupyter/notebook_cookie_secret
[W 10:36:51.635 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 10:36:51.645 NotebookApp] Error loading server extension jupyter_tensorboard
    Traceback (most recent call last):
      File "/opt/packages/anaconda/anaconda3-5.1.0/lib/python3.6/site-packages/notebook/notebookapp.py", line 1451, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/opt/packages/anaconda/anaconda3-5.1.0/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_tensorboard'
[I 10:36:51.677 NotebookApp] JupyterLab beta preview extension loaded from /opt/packages/anaconda/anaconda3-5.1.0/lib/python3.6/site-packages/jupyterlab
[I 10:36:51.677 NotebookApp] JupyterLab application directory is /opt/packages/anaconda/anaconda3-5.1.0/share/jupyter/lab
[I 10:36:51.683 NotebookApp] Serving notebooks from local directory: /home/julian
[I 10:36:51.684 NotebookApp] 0 active kernels
[I 10:36:51.684 NotebookApp] The Jupyter Notebook is running at:
[I 10:36:51.684 NotebookApp] http://[all ip addresses on your system]:15108/node/gpu058-2.ib.bridges.psc.edu/15108/
[I 10:36:51.684 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

**Comment by julianx** [comment]
Correspondence added
===
This is working now.

The VMs need specific routes to get to the hosts that do not have OPA, xl* and gpu058. 
The conf file had the lines commented out, possibly because the gateway was incorrect. 

#> diff /tmp/vm028.bridges.psc.edu.yaml vm028.bridges.psc.edu.yaml
12c12
< #    - bridges::networking::gateway_routes
---
>     - bridges::networking::gateway_routes
25,26c25,26
< # bridges::networking::gateway_routes::dev:       'eth1'
< # bridges::networking::gateway_routes::gateway:   '10.4.131.1'
---
> bridges::networking::gateway_routes::dev:       'eth1'
> bridges::networking::gateway_routes::gateway:   '10.4.138.1'
root@br002:/opt/puppetlabs/code/environments/bridges/hieradata/nodes #>

===

A test was performed and it is working as expected now. 
![image](https://user-images.githubusercontent.com/566664/86791635-bf185a80-c037-11ea-84b9-a7b1eadd4106.png)
